-- Tariq seed: Marrakech catalogue (20 products and their add-ons).
-- ALL PRICES ARE PLACEHOLDERS until the partner's cost sheet arrives.
-- Generated from data/catalogue.json by scripts/gen-seed.mjs. Do not edit by hand.

begin;
delete from product_addons where product_id in (select id from products where city = 'marrakech');

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('airport', 'marrakech', 'trf', 'lead', 'Airport transfer', 'Transfer', 'Driver waits at arrivals with your name. Flight tracked, 60 min free waiting.', 'Any time, day or night', '20–30 min', 6, '20 min', 12, 18, 'car', 3, null, null, 'plane', null, array['Driver waits at arrivals with a name board', 'Flight tracked, 60 minutes of free waiting', 'Walked to your riad door when the car can''t reach it']::text[], array['Private air-conditioned car, up to 3 guests with luggage', 'Meet and greet at arrivals', 'Fuel and airport fees']::text[], array['Porter (add-on)', 'Tips']::text[], array['Add your flight number in the notes so we can track delays', 'Inside the medina, cars stop at the nearest access point. A porter carries bags to the door']::text[], 10, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('ret', 'airport', 'Return transfer to the airport', 12, 'car', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('porter', 'airport', 'Porter to the riad door', 5, 'car', false, 20);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('sim', 'airport', 'Local SIM, 20 GB, ready in the car', 12, 'unit', false, 30);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('seat', 'airport', 'Child car seat fitted', 6, 'unit', false, 40);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('lastday', 'marrakech', 'trf', 'gap', 'Last day, bags in the van', 'Transfer', 'Checkout at noon, flight at night. Your bags ride with you all day, then we drop you at the airport.', 'Pickup at checkout', 'Checkout to flight', 6, 'your last day', 25, null, 'car', 4, null, null, 'plane', null, array['No locker, no second taxi', 'Bags stay locked in the van while you use your last day', 'Dropped at the airport in time for your flight']::text[], array['Van and driver from checkout to the airport', 'Secure luggage in the locked vehicle', 'Airport drop-off']::text[], array['Activities during the day (add-ons)', 'Meals']::text[], array['Tell us your flight time in the notes', 'Valuables and passports stay with you']::text[], 20, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('trip', 'lastday', 'Add a half-day trip to Ourika on the way', 20, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('hammam', 'lastday', 'Hammam and shower before the flight', 25, 'pp', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('dinner', 'marrakech', 'trf', 'gap', 'Dinner out, there and back', 'Transfer', 'Tell us the restaurant and time. We book the table and drive you there and back to the medina.', 'Any evening', 'Evening', 5, 'evening', 14, null, 'car', 4, null, null, 'city', null, array['Tell us the restaurant and time, we book the table', 'Driver waits nearby or comes back when you call', 'Home safe to the medina, even after midnight']::text[], array['Table booking at the restaurant you name', 'Return transfer for up to 4 guests']::text[], array['Your meal and drinks', 'Returns after midnight (add-on)']::text[], array['We book the restaurant you choose. We don''t recommend or take commission from restaurants']::text[], 30, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('late', 'dinner', 'Late return after midnight', 6, 'car', false, 10);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('ourika', 'marrakech', 'exc', 'lead', 'Ourika Valley day trip', 'Day trip', 'Atlas foothills, a Berber house visit and the Setti Fatma waterfalls.', 'Pickup 8:30', '8 hours', 63, '1 h 10', 22, 29, 'pp', null, 70, null, 'valley', null, array['Drive into the High Atlas foothills', 'Tea in a Berber family house', 'Walk to the Setti Fatma waterfalls with a local guide']::text[], array['Shared air-conditioned minivan', 'Pickup and drop-off at your riad or hotel', 'Driver']::text[], array['Lunch (add-on)', 'Waterfall guide tip', 'Private car (upgrade)']::text[], array['Wear shoes with grip for the waterfall path', 'The walk to the upper falls includes some rock scrambling']::text[], 40, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lunch', 'ourika', 'Tagine lunch by the river', 10, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('kit', 'ourika', 'Day kit: water, snacks, sunscreen', 9, 'pp', false, 20);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('quad', 'ourika', '1 h quad ride on the way back', 35, 'pp', false, 30);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('ouzoud', 'marrakech', 'exc', 'core', 'Ouzoud Waterfalls', 'Day trip', 'The tallest falls in North Africa, olive groves and macaques on the path down.', 'Pickup 7:30', '10 hours', 150, '2 h 45', 24, 27, 'pp', null, 110, null, 'falls', null, array['The tallest waterfalls in North Africa', 'Barbary macaques on the path down', 'Olive groves and mills of the Azilal region']::text[], array['Shared air-conditioned minivan', 'Pickup and drop-off', 'Guided walk to the base of the falls']::text[], array['Lunch (add-on)', 'Boat ride (add-on)']::text[], array['Around 2 h 45 each way by road', 'Don''t feed the monkeys']::text[], 50, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lunch', 'ouzoud', 'Lunch at the falls', 10, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('boat', 'ouzoud', 'Boat ride under the falls', 5, 'pp', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('essaouira', 'marrakech', 'exc', 'core', 'Essaouira day trip', 'Day trip', 'The walled port on the Atlantic. Argan cooperative stop, 5 hours free in town.', 'Pickup 7:30', '11 hours', 190, '2 h 45', 25, 29, 'pp', null, 120, null, 'ocean', null, array['The walled port town on the Atlantic', 'Stop at an argan oil cooperative', 'About 5 hours free in the medina and harbour']::text[], array['Shared air-conditioned minivan', 'Pickup and drop-off', 'Free time in town']::text[], array['Lunch (add-on)', 'Medina guide (add-on)']::text[], array['Bring a jacket, the ocean wind is cool even in summer']::text[], 60, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('fish', 'essaouira', 'Grilled fish lunch at the harbour', 15, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('guide', 'essaouira', '2 h medina guide', 10, 'pp', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('imlil', 'marrakech', 'exc', 'core', 'Atlas Mountains & Imlil', 'Day trip', 'Three valleys, a mountain village walk and mint tea facing Toubkal.', 'Pickup 8:30', '8 hours', 65, '1 h 30', 29, null, 'pp', null, 80, null, 'atlas', null, array['Three valleys of the High Atlas', 'Walk through a mountain village', 'Mint tea with a view of Toubkal']::text[], array['Shared air-conditioned minivan', 'Pickup and drop-off', 'Local mountain guide for the walk']::text[], array['Lunch (add-on)', 'Mule (add-on)', 'Trek kit (add-on)']::text[], array['Easy to moderate walking, about 2 hours', 'It is cooler in the mountains, bring a layer']::text[], 70, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('kit', 'imlil', 'Trek day kit waiting in the van', 12, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lunch', 'imlil', 'Lunch in a village house', 10, 'pp', false, 20);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('mule', 'imlil', 'Mule for the walk', 12, 'unit', false, 30);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('abh', 'marrakech', 'exc', 'core', 'Aït Benhaddou & Ouarzazate', 'Day trip', 'Over the Tizi n''Tichka pass to the earthen ksar and the film studios.', 'Pickup 7:00', '12 hours', 185, '3 h', 39, null, 'pp', null, 140, null, 'ksar', null, array['Cross the Tizi n''Tichka pass, 2,260 m', 'The earthen ksar of Aït Benhaddou', 'Ouarzazate and its film studios']::text[], array['Shared air-conditioned minivan', 'Pickup and drop-off', 'Driver']::text[], array['Lunch (add-on)', 'Studio entry (add-on)', 'Local guide in the ksar']::text[], array['A long day, about 3 hours each way on mountain roads', 'Motion-sickness bands help on the pass']::text[], 80, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lunch', 'abh', 'Lunch facing the ksar', 12, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('studio', 'abh', 'Film studios entry', 8, 'pp', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('sahara3', 'marrakech', 'des', 'cow', '3-day Sahara, Merzouga', '3 days', 'Tichka pass, Aït Benhaddou, Dades gorges, a camel trek into the Erg Chebbi dunes and a night in camp.', 'Pickup 7:00', '3 days, 2 nights', 560, '3 days', 139, null, 'pp', null, 420, 'Best seller', 'dunes', null, array['Tizi n''Tichka pass and Aït Benhaddou', 'A night by the Dades gorges', 'Camel trek into the Erg Chebbi dunes and a night in camp']::text[], array['Transport and driver for 3 days', '1 night hotel, 1 night desert camp', '2 breakfasts and 2 dinners', 'Camel trek at sunset']::text[], array['Lunches', 'Luxury camp (upgrade)', '4x4 dune ride (add-on)']::text[], array['Long driving days, about 9 hours to Merzouga', 'Desert nights are cold from November to March', 'Bring a small bag for the camp night']::text[], 90, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lux', 'sahara3', 'Luxury camp, private bathroom', 60, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('dkit', 'sahara3', 'Desert night kit: scarf, headlamp, warm socks', 15, 'pp', false, 20);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('4x4', 'sahara3', '4x4 dune ride at sunset', 30, 'pp', false, 30);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('zagora', 'marrakech', 'des', 'core', '2-day desert, Zagora', '2 days', 'Aït Benhaddou, the Draa valley and a night in a desert camp.', 'Pickup 7:00', '2 days, 1 night', 360, '2 days', 85, null, 'pp', null, 260, null, 'palms', null, array['Aït Benhaddou on the way', 'The palm groves of the Draa valley', 'A night in a desert camp']::text[], array['Transport and driver', '1 night desert camp', 'Dinner and breakfast', 'Camel ride']::text[], array['Lunches', 'Luxury tent (upgrade)']::text[], array['Zagora has small dunes. For the big Sahara dunes, choose the 3-day Merzouga trip']::text[], 100, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lux', 'zagora', 'Luxury tent with bathroom', 45, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('dkit', 'zagora', 'Desert night kit', 15, 'pp', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('balloon', 'marrakech', 'act', 'cow', 'Hot air balloon at sunrise', 'Activity', 'One hour over the palm groves and Atlas foothills. Berber breakfast after landing.', 'Pickup 5:30', '4 hours with transfers', 30, 'sunrise', 159, null, 'pp', null, null, 'Signature', 'balloon', null, array['One hour in the air at sunrise', 'Over the palm groves with the Atlas behind', 'Berber breakfast after landing']::text[], array['Pickup and drop-off', '1 hour flight', 'Berber breakfast', 'Flight certificate']::text[], array['VIP basket (upgrade)', 'Photo and video pack (add-on)']::text[], array['Flights depend on the weather. If cancelled, you choose another date or a full refund', 'Not suitable during pregnancy or for children under 5']::text[], 110, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('vip', 'balloon', 'VIP basket, max 8 people', 60, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('photos', 'balloon', 'Photo and video pack', 25, 'unit', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('agafay', 'marrakech', 'act', 'cow', 'Agafay dinner & stargazing', 'Evening', 'Sunset in the stone desert, camel ride, three-course dinner and fire show.', 'Pickup 16:00', '6 hours', 40, '45 min', 69, 86, 'pp', null, null, 'Most booked', 'stone', null, array['Sunset over the stone desert', 'Camel ride before dinner', 'Three-course dinner, music and fire show']::text[], array['Return transport', '20-minute camel ride', 'Three-course dinner and mint tea', 'Live entertainment']::text[], array['Drinks', 'Quad or buggy (add-ons)']::text[], array['Agafay is a stone desert 40 minutes away, not the Sahara', 'Bring a warm layer, evenings are cool']::text[], 120, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('quad', 'agafay', '1 h quad ride before dinner', 35, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('buggy', 'agafay', '1 h buggy, 2 seats', 60, 'unit', false, 20);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lux', 'agafay', 'Luxury camp table', 20, 'pp', false, 30);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('quad', 'marrakech', 'act', 'core', 'Quad biking in Agafay', 'Activity', 'Two hours on desert tracks with a guide, mint tea in a Berber tent.', 'Pickup 9:00 or 14:00', '4 hours with transfers', 40, '2 h', 39, null, 'pp', null, null, null, 'quad', null, array['Two hours on desert tracks', 'Guide rides with the group', 'Mint tea in a Berber tent']::text[], array['Pickup and drop-off', 'Quad, helmet and scarf', 'Guide']::text[], array['Sunset dinner (add-on)']::text[], array['Driving licence not needed', 'Minimum age 16 to drive, children can ride as passengers']::text[], 130, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('dinner', 'quad', 'Stay for sunset dinner', 45, 'pp', true, 10);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('camel', 'marrakech', 'act', 'lead', 'Camel ride in the Palmeraie', 'Activity', 'One hour through the palm groves at sunset, tea with a Berber family.', 'Pickup 16:30', '2 hours', 12, '25 min', 19, 25, 'pp', null, null, null, 'palms', null, array['One hour through the palm groves', 'Golden light at sunset', 'Tea and bread with a Berber family']::text[], array['Pickup and drop-off', 'Camel and handler', 'Tea']::text[], array['Quad (add-on)']::text[], array['Suitable for children with an adult']::text[], 140, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('quad', 'camel', 'Add 1 h quad ride', 30, 'pp', true, 10);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('henna', 'marrakech', 'svc', 'gap', 'Henna artist at your riad', 'At your riad', 'She comes to you in the evening. Hands, from a simple line to a full bridal design.', '18:00 to 22:00', '1–2 hours', 0, 'at your riad', 25, null, 'pp', null, null, null, 'riad', null, array['She comes to your riad in the evening', 'From a simple line to a full bridal design', 'Natural henna only']::text[], array['Henna artist at your riad or hotel', 'Natural henna paste']::text[], array['Feet design (add-on)']::text[], array['We use natural henna only, never black henna', 'Let it dry 1–2 hours and avoid water for the night']::text[], 150, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('feet', 'henna', 'Add feet design', 10, 'pp', true, 10);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('massage', 'marrakech', 'svc', 'gap', 'Massage at your riad, 60 min', 'At your riad', 'Argan oil massage in your room. Therapist brings the table and linen.', '10:00 to 21:00', '60 minutes', 0, 'at your riad', 45, null, 'pp', null, null, null, 'riad', null, array['In your room, no taxi, no spa queue', 'Argan oil massage', 'Therapist brings the table and linen']::text[], array['Qualified therapist', 'Massage table, oils and linen']::text[], array['90 minutes (upgrade)']::text[], array['Tell us in the notes if you prefer a female or male therapist']::text[], 160, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('x90', 'massage', 'Make it 90 minutes', 20, 'pp', true, 10);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('chef', 'marrakech', 'svc', 'gap', 'Private chef dinner in your riad', 'At your riad', 'A home cook shops, cooks and serves a three-course Moroccan dinner where you stay.', 'Served from 19:30', 'Evening', 0, 'at your riad', 35, null, 'pp', null, null, null, 'riad', null, array['A home cook shops at the souk for you', 'Three-course Moroccan dinner in your riad', 'Cleaned up after']::text[], array['Shopping and ingredients', 'Cooking and service', 'Clean-up']::text[], array['Drinks', 'Cooking lesson (add-on)']::text[], array['Your riad needs to allow use of its kitchen. We check for you', 'Tell us allergies in the notes']::text[], 170, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('lesson', 'chef', 'Cooking lesson before dinner', 15, 'pp', true, 10);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('trekkit', 'marrakech', 'kit', 'gap', 'Trek day kit', 'Kit', 'Almonds, dates, protein bar, electrolytes, 2 L water, sunscreen, blister plasters.', 'Waiting in your van', 'Delivered', 0, 'delivered', 12, null, 'pp', null, null, null, 'kit', null, array['Packed for you, nothing to shop for', 'Waiting in your van on the way to the mountains', 'Everything a day on the trail needs']::text[], array['Almonds, dates, protein bar', 'Electrolyte sachets', '2 L water', 'Sunscreen and blister plasters']::text[], array['Toubkal upgrade (add-on)', 'Crampons and poles (add-on)']::text[], array['One kit per person']::text[], 180, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('summit', 'trekkit', 'Toubkal upgrade: headlamp, gloves, hand warmers', 17, 'pp', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('crampons', 'trekkit', 'Crampons and poles rental', 9, 'pp', false, 20);

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('desertkit', 'marrakech', 'kit', 'gap', 'Desert night kit', 'Kit', 'Scarf for the sand, headlamp, wet wipes, lip balm, warm socks, power bank.', 'Waiting in your van', 'Delivered', 0, 'delivered', 15, null, 'pp', null, null, null, 'kit', null, array['For the cold desert night', 'Waiting in your van on day 1', 'Keep the scarf, it''s yours']::text[], array['Scarf for sun and sand', 'Headlamp', 'Wet wipes and lip balm', 'Warm socks', 'Power bank']::text[], array[]::text[], array['One kit per person']::text[], 190, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;

insert into products (id, city, category, role, title, subtitle, blurb, timing, duration, km, drive_time, price_eur, was_eur, per, cap, private_per_car, badge, scene, image_url, highlights, includes, excludes, know_before, sort, active)
values ('baby', 'marrakech', 'kit', 'gap', 'Baby kit for your stay', 'Baby', 'Travel cot, high chair and car seat, delivered and set up at your riad. Collected when you leave.', 'Delivered the day you arrive', 'Your whole stay', 0, 'for your stay', 39, null, 'flat', null, null, null, 'baby', null, array['Cot, high chair and car seat, set up before you arrive', 'Car seat fitted in your airport van', 'Collected when you leave']::text[], array['Travel cot with mattress and sheet', 'High chair', 'Car seat or booster by age', 'Delivery, set-up and collection']::text[], array['Baby carrier (add-on)', 'Pushchair (add-on)']::text[], array['Pushchairs are hard work on medina lanes and steps. A carrier is easier', 'Tell us your baby''s age in the notes']::text[], 200, true)
on conflict (id) do update set city = excluded.city, category = excluded.category, role = excluded.role, title = excluded.title, subtitle = excluded.subtitle, blurb = excluded.blurb, timing = excluded.timing, duration = excluded.duration, km = excluded.km, drive_time = excluded.drive_time, price_eur = excluded.price_eur, was_eur = excluded.was_eur, per = excluded.per, cap = excluded.cap, private_per_car = excluded.private_per_car, badge = excluded.badge, scene = excluded.scene, highlights = excluded.highlights, includes = excluded.includes, excludes = excluded.excludes, know_before = excluded.know_before, sort = excluded.sort, active = excluded.active;
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('carrier', 'baby', 'Baby carrier for the medina lanes', 10, 'unit', true, 10);
insert into product_addons (id, product_id, label, eur, per, popular, sort) values ('pram', 'baby', 'Pushchair for Gueliz and gardens', 12, 'unit', false, 20);

commit;
