// All customer-facing strings live here so a translation layer can wrap this later.
export const copy = {
  brand: "Tariq",
  city: "Marrakech",

  nav: {
    main: "Main",
    tabs: "Tabs",
    explore: "Explore",
    dayTrips: "Day trips",
    desert: "Multi-day tours",
    tours: "Activities",
    tickets: "Tickets",
    transfers: "Transfers",
    atRiad: "Concierge",
    kits: "Kits & baby",
    ask: "Ask Tariq",
    packages: "Packages",
    plan: "Plan my trip",
    myTrip: "My trip",
    book: "Book",
    tariq: "Tariq",
    currency: "Currency",
  },

  categories: {
    all: "All",
    exc: "Day trips",
    des: "Multi-day tours",
    act: "Activities",
    tkt: "Tickets",
    trf: "Transfers",
    svc: "Concierge",
    kit: "Kits & baby",
  },

  hero: {
    h1: "Everything for your Marrakech trip.",
    h1Em: "One place.",
    placeholder: "Landing at 2am with a baby. What do I book?",
    askBtn: "Ask Tariq",
  },

  promises: [
    "Pay on arrival",
    "Pickup time on WhatsApp",
    "Licensed transport",
    "No shopping stops",
    "Free cancellation up to 24 h",
  ],

  book: { h: "Book", p: "Final prices. No booking fees." },
  rails: {
    seeAll: "See all",
    browseH: "Browse by what you need",
    browseAll: "Everything",
    count: (n: number) => `${n} ${n === 1 ? "option" : "options"}`,
  },

  listing: {
    date: "Date",
    guests: "Guests",
    fewer: "Fewer guests",
    more: "More guests",
    sort: "Sort",
    sortRecommended: "Recommended",
    sortLow: "Price low to high",
    sortHigh: "Price high to low",
    results: (n: number) => `${n} ${n === 1 ? "result" : "results"}`,
    freeCancel: "Free cancellation",
    payOnArrival: "Pay on arrival",
    save: "Save",
    unsave: "Remove from saved",
    empty: "Nothing in this category yet.",
  },
  solved: {
    h: "Solved before you ask",
    p: "The things nobody else sorts out for you. Added to any booking, delivered in the van that's already coming.",
  },
  how: [
    { b: "Book in a minute", s: "Pick a trip or a fix, choose the date, tell us your riad. Nothing to pay now." },
    { b: "Get your pickup time", s: "The evening before, your driver's name and exact time arrive on WhatsApp." },
    { b: "Pay on the day", s: "Cash in dirhams or euros, or card. You get a receipt." },
  ],

  concierge: {
    h: "Ask Tariq",
    p: "Your Marrakech concierge. Transfers, trips, kits, a henna artist at 9pm. Ask anything.",
    placeholder: "Ask about your trip",
    send: "Send",
    hi: "Hi, I'm Tariq. Tell me your dates, who's travelling and what's worrying you. I'll sort the rest.",
    thinking: "Tariq is thinking…",
    offline: "I can't reach the concierge right now, so here's what matches in the catalogue:",
    nomatch: "Nothing matches that exactly. Message the team on WhatsApp and a person will sort it:",
    error: "Something went wrong on my side. Try again in a moment.",
    suggestions: [
      "Landing at 2am, 2 adults and a baby",
      "We have 4 days, what should we book?",
      "Checkout at noon, flight at 9pm",
      "Is Agafay the Sahara?",
    ],
  },

  trip: {
    h: "My trip",
    p: "Everything you booked, in order.",
    empty: "Nothing booked yet. Start with the airport pickup, or ask Tariq what fits your dates.",
    total: "To pay on the day",
    paid: "Paid",
    wa: "Send my trip to WhatsApp",
    saved: "Saved",
  },

  price: {
    pp: "per person",
    car: "per car",
    flat: "per booking",
    unit: "each",
    from: "from",
  },

  checkout: {
    date: "Date",
    guests: "Guests",
    pickupAt: "Your riad or hotel",
    pickupPlaceholder: "Riad name, derb or hotel",
    name: "Full name",
    phone: "WhatsApp number",
    phonePlaceholder: "+33 6 12 34 56 78",
    notes: "Notes (flight number, restaurant, allergies, baby's age)",
    total: "Total, paid on the day",
    confirm: "Confirm booking",
    noPay: "Nothing is charged now. Free cancellation up to 24 h before.",
    shared: "Shared",
    sharedS: "Small group minivan",
    private: "Private",
    privateS: "Your own car and driver",
    inclPrivate: "incl. private car",
    extras: "Add to it",
    popular: "Popular",
    base: "Booking",
    continue: "Continue",
    back: "Back",
    participants: "Participants",
    checkoutH: "Complete your booking",
    yourBooking: "Your booking",
    edit: "Edit",
    done: "Done",
    chooseOption: "Choose an option",
    summary: "Booking summary",
    cancelPolicy: "Free cancellation up to 24 hours before. Prepaid bookings are refunded in full.",
    payH: "How would you like to pay?",
    payNow: "Pay now",
    payNowS: "PayPal or card via PayPal. Instant confirmation, nothing to pay on the day.",
    payLater: "Reserve now, pay on the day",
    payLaterS: "Cash (dirhams or euros) or card to your driver. Nothing charged now.",
    payWith: (amount: string) => `Pay ${amount} with PayPal`,
    guideCurrency: (shown: string, eur: string, mad: string) =>
      `${shown} is a guide at today's rate. You pay ${eur} (or ${mad}), online in euros or on the day in euros or dirhams.`,
    redirecting: "Taking you to PayPal…",
    paypalNote: "You'll be taken to PayPal to pay securely, then brought back here.",
    paidNotice: "Nothing is charged until you approve the payment on PayPal.",
    cancelled: "Payment cancelled. Nothing was charged. Choose how you'd like to pay.",
    failed: "The payment didn't go through. Nothing was charged. Try again or choose to pay on the day.",
    contactH: "Contact details",
    contactP: "We send your pickup time and driver's name to this WhatsApp number the evening before.",
    standard: "Standard",
    noExtras: "Nothing to add to this one. Continue to your details.",
    sending: "Confirming…",
    shareFail: "Something went wrong. Please try again, or message us on WhatsApp.",
    errors: {
      date: "Choose a date from tomorrow onwards.",
      pickup: "Tell us where you're staying.",
      name: "Add the name of the lead guest.",
      phone: "Add a WhatsApp number with country code, for example +33 6 12 34 56 78.",
    },
  },

  done: {
    h: "Booking confirmed",
    p: "Your pickup time and driver's name arrive on WhatsApp the evening before.",
    ref: "Reference",
    booking: "Booking",
    when: "Date",
    who: "Guests",
    where: "Pickup",
    with: "Extras",
    pay: "To pay on the day",
    sendWa: "Send to WhatsApp",
    seeTrip: "See my trip",
    xsell: "Often added next",
    add: "Add",
    notStored: "Tap Send to WhatsApp so the team has your booking.",
    paidOnline: "Paid with PayPal",
    nothingDue: "Nothing to pay on the day",
    payPending: "We haven't received your payment yet. If you completed it on PayPal, it will appear here shortly; otherwise message the team on WhatsApp.",
    close: "Close",
    missing: "We can't find this booking on this device. Message the team on WhatsApp with your reference and we'll sort it.",
  },

  product: {
    flexH: "Free cancellation",
    flexP: "Cancel up to 24 hours in advance for a full refund.",
    laterH: "Reserve now, pay later",
    laterP: "Book your spot and pay nothing today.",
    highlights: "Highlights",
    about: "About this booking",
    itinerary: "How it runs",
    totalFor: "Total for",
    guest: "guest",
    guests: "guests",
    cars: "cars",
    mostAdd: "Most travellers add:",
    payDay: "pay on the day",
    includes: "What's included",
    excludes: "Not included",
    pickupH: "Pickup and meeting",
    pickupRiad: "We come to your riad or hotel. You tell us the name when you book.",
    pickupMedina: "Inside the medina, cars can't reach most doors. We stop at the nearest car access point and meet you there. A porter can be added to carry bags.",
    pickupTime: "Your exact pickup time and driver's name arrive on WhatsApp the evening before.",
    know: "Know before you go",
    alsoLike: "You might also like",
    check: "Check availability",
    factPickup: "Pickup included",
    factAtRiad: "At your riad",
    factDelivered: "Delivered",
    factShared: "Shared minivan",
    factSharedPrivate: "Shared minivan, private option",
    factPrivateCar: "Private car",
    factCancel: "Free cancellation 24 h",
    factPay: "Pay on arrival",
    keyFacts: "Key facts",
  },

  footer: {
    tagline: "Tariq · Marrakech",
    wa: "WhatsApp, daily 8:00–22:00:",
    dispatch: "Dispatch",
  },
} as const;

export type Copy = typeof copy;
